fails:Exception#cause is set for internal errors caused by user errors
